# fly.toml app configuration file generated for rss-test on 2023-08-02T15:08:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rss-test"
primary_region = "fra"

[build]

[env]
  PORT = "8080"
  base_url = 'https://rss-test.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
