version = 0.1
[default.deploy.parameters]
stack_name = "scheduled-lambdas"
resolve_s3 = true
s3_prefix = "scheduled-lambdas"
region = "us-east-2"
profile = "johanan-personal-cli"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []